#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLI_CONFIG="${HOME}/.render/cli.yaml"
OWNER_ID="tea-d8leelq8qa3s73er8mdg"
REPO="https://github.com/EBay1992/NexusWorkspaceEngine"
BRANCH="main"
DB_ID="${RENDER_DB_ID:-dpg-d9aik9pkh4rs73dqsru0-a}"

api_key() {
  python3 -c "import yaml; print(yaml.safe_load(open('${CLI_CONFIG}'))['api']['key'])"
}

api_post() {
  curl -sS -X POST "https://api.render.com/v1/services" \
    -H "Authorization: Bearer $(api_key)" \
    -H "Content-Type: application/json" \
    -d @"$1"
}

export JWT_KEY ADMIN_PW DB_URL

JWT_KEY="$(openssl rand -base64 32)"
ADMIN_PW="$(openssl rand -base64 18)"
DB_URL="$(curl -sS -H "Authorization: Bearer $(api_key)" \
  "https://api.render.com/v1/postgres/${DB_ID}/connection-info" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['internalConnectionString'])")"

mkdir -p "${ROOT}/.render-local"
cat > "${ROOT}/.render-local/secrets.env" <<EOF
# Generated by scripts/render-provision.sh — do not commit
ADMIN_EMAIL=admin@ehsanbayranvand.tech
ADMIN_PASSWORD=${ADMIN_PW}
JWT_SIGNING_KEY=${JWT_KEY}
DATABASE_URL=${DB_URL}
EOF
chmod 600 "${ROOT}/.render-local/secrets.env"

python3 - <<'PY' > /tmp/nexus-gw.json
import json, os
print(json.dumps({
  "type": "web_service",
  "name": "nexus-orbit-gateway",
  "ownerId": "tea-d8leelq8qa3s73er8mdg",
  "repo": "https://github.com/EBay1992/NexusWorkspaceEngine",
  "branch": "main",
  "autoDeploy": "yes",
  "envVars": [
    {"key": "DATABASE_URL", "value": os.environ["DB_URL"]},
    {"key": "JWT_SIGNING_KEY", "value": os.environ["JWT_KEY"]},
    {"key": "NEXT_PUBLIC_APP_URL", "value": "https://nexus.ehsanbayranvand.tech"},
    {"key": "RELAY_WS_URL", "value": "wss://relay.nexus.ehsanbayranvand.tech/orbit"},
    {"key": "ADMIN_EMAIL", "value": "admin@ehsanbayranvand.tech"},
    {"key": "ADMIN_PASSWORD", "value": os.environ["ADMIN_PW"]},
  ],
  "serviceDetails": {
    "runtime": "docker",
    "plan": "free",
    "region": "frankfurt",
    "healthCheckPath": "/health",
    "envSpecificDetails": {
      "dockerfilePath": "services/gateway/Dockerfile",
      "dockerContext": ".",
    },
  },
}))
PY

python3 - <<'PY' > /tmp/nexus-relay.json
import json, os
print(json.dumps({
  "type": "web_service",
  "name": "nexus-orbit-relay",
  "ownerId": "tea-d8leelq8qa3s73er8mdg",
  "repo": "https://github.com/EBay1992/NexusWorkspaceEngine",
  "branch": "main",
  "autoDeploy": "yes",
  "envVars": [
    {"key": "JWT_SIGNING_KEY", "value": os.environ["JWT_KEY"]},
    {"key": "RELAY_HOST", "value": "0.0.0.0"},
    {"key": "RELAY_DEV_NO_AUTH", "value": "false"},
    {"key": "RELAY_REDIS_ENABLED", "value": "false"},
    {"key": "NODE_ENV", "value": "production"},
  ],
  "serviceDetails": {
    "runtime": "docker",
    "plan": "free",
    "region": "frankfurt",
    "healthCheckPath": "/health",
    "envSpecificDetails": {
      "dockerfilePath": "apps/relay/Dockerfile",
      "dockerContext": ".",
    },
  },
}))
PY

python3 - <<'PY' > /tmp/nexus-web.json
import json
print(json.dumps({
  "type": "web_service",
  "name": "nexus-orbit-web",
  "ownerId": "tea-d8leelq8qa3s73er8mdg",
  "repo": "https://github.com/EBay1992/NexusWorkspaceEngine",
  "branch": "main",
  "autoDeploy": "yes",
  "envVars": [
    {"key": "NEXT_PUBLIC_APP_URL", "value": "https://nexus.ehsanbayranvand.tech"},
    {"key": "NEXT_PUBLIC_GATEWAY_URL", "value": "https://api.nexus.ehsanbayranvand.tech"},
    {"key": "NEXT_PUBLIC_RELAY_WS_URL", "value": "wss://relay.nexus.ehsanbayranvand.tech/orbit"},
    {"key": "NODE_ENV", "value": "production"},
    {"key": "HOSTNAME", "value": "0.0.0.0"},
  ],
  "serviceDetails": {
    "runtime": "docker",
    "plan": "free",
    "region": "frankfurt",
    "healthCheckPath": "/",
    "envSpecificDetails": {
      "dockerfilePath": "apps/web/Dockerfile",
      "dockerContext": ".",
    },
  },
}))
PY

echo "Creating nexus-orbit-gateway..."
api_post /tmp/nexus-gw.json | python3 -m json.tool | head -25

echo "Creating nexus-orbit-relay..."
api_post /tmp/nexus-relay.json | python3 -m json.tool | head -20

echo "Creating nexus-orbit-web..."
api_post /tmp/nexus-web.json | python3 -m json.tool | head -20

echo ""
echo "Secrets written to .render-local/secrets.env"
echo "Dashboard: https://dashboard.render.com/"
